services:
  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${DB_USERNAME}  # Loaded from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Loaded from .env
      POSTGRES_DB: ${DB_DATABASE}  # Loaded from .env
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend
    volumes:
      - .:/app  # Optional: Mount the app directory for live reload during development

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - '5435:5432' # Host port 5435 mapped to container port 5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}  # Loaded from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Loaded from .env
      POSTGRES_DB: ${DB_DATABASE}  # Loaded from .env
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - '6382:6379' # Host port 6382 mapped to container port 6379
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
